export const users = [
  {
    id: 1,
    name: "Skell",
    age: 38,
    email: "swilkerson0@guardian.co.uk",
    country: "North Korea",
    birthday: "9/8/2023",
  },
  {
    id: 2,
    name: "Kris",
    age: 50,
    email: "ksturge1@edublogs.org",
    country: "China",
    birthday: "4/22/2023",
  },
  {
    id: 3,
    name: "Darby",
    age: 77,
    email: "dscintsbury2@livejournal.com",
    country: "Venezuela",
    birthday: "6/14/2023",
  },
  {
    id: 4,
    name: "Shandeigh",
    age: 50,
    email: "sbollini3@mozilla.com",
    country: "Yemen",
    birthday: "7/15/2023",
  },
  {
    id: 5,
    name: "Phedra",
    age: 30,
    email: "pprestedge4@merriam-webster.com",
    country: "China",
    birthday: "12/22/2022",
  },
  {
    id: 6,
    name: "Jeremiah",
    age: 25,
    email: "jflahive5@discovery.com",
    country: "China",
    birthday: "5/5/2023",
  },
  {
    id: 7,
    name: "Waly",
    age: 58,
    email: "wfippe6@fc2.com",
    country: "Ukraine",
    birthday: "10/20/2023",
  },
  {
    id: 8,
    name: "Miles",
    age: 26,
    email: "mtoffanelli7@ow.ly",
    country: "Indonesia",
    birthday: "9/10/2023",
  },
  {
    id: 9,
    name: "Vita",
    age: 24,
    email: "vhastin8@msu.edu",
    country: "Germany",
    birthday: "10/28/2023",
  },
  {
    id: 10,
    name: "Killian",
    age: 43,
    email: "kriba9@rakuten.co.jp",
    country: "China",
    birthday: "3/16/2023",
  },
  {
    id: 11,
    name: "Ambrose",
    age: 60,
    email: "aasburya@godaddy.com",
    country: "China",
    birthday: "3/8/2023",
  },
  {
    id: 12,
    name: "Sonja",
    age: 77,
    email: "stunnicliffeb@google.co.uk",
    country: "Japan",
    birthday: "4/12/2023",
  },
  {
    id: 13,
    name: "Krystalle",
    age: 39,
    email: "kbarkshirec@google.ca",
    country: "Bosnia and Herzegovina",
    birthday: "9/23/2023",
  },
  {
    id: 14,
    name: "Robbie",
    age: 24,
    email: "rjestecod@senate.gov",
    country: "China",
    birthday: "7/1/2023",
  },
  {
    id: 15,
    name: "Marilyn",
    age: 58,
    email: "mweiche@samsung.com",
    country: "Sri Lanka",
    birthday: "10/11/2023",
  },
  {
    id: 16,
    name: "Jammal",
    age: 28,
    email: "jbuncomf@usatoday.com",
    country: "Guatemala",
    birthday: "9/23/2023",
  },
  {
    id: 17,
    name: "Orella",
    age: 48,
    email: "odavidsg@github.com",
    country: "Brazil",
    birthday: "12/24/2022",
  },
  {
    id: 18,
    name: "Tadio",
    age: 61,
    email: "twrothamh@senate.gov",
    country: "Poland",
    birthday: "4/6/2023",
  },
  {
    id: 19,
    name: "Gray",
    age: 65,
    email: "gtungayi@eventbrite.com",
    country: "Finland",
    birthday: "7/1/2023",
  },
  {
    id: 20,
    name: "Ignatius",
    age: 63,
    email: "ikreutzerj@hhs.gov",
    country: "Finland",
    birthday: "8/23/2023",
  },
  {
    id: 21,
    name: "Shell",
    age: 43,
    email: "sroysek@chicagotribune.com",
    country: "Argentina",
    birthday: "4/24/2023",
  },
  {
    id: 22,
    name: "Shelia",
    age: 73,
    email: "ssaziol@hao123.com",
    country: "France",
    birthday: "2/12/2023",
  },
  {
    id: 23,
    name: "Patty",
    age: 63,
    email: "pflageulm@mysql.com",
    country: "Mexico",
    birthday: "9/29/2023",
  },
  {
    id: 24,
    name: "Cari",
    age: 77,
    email: "cpetruskevichn@pbs.org",
    country: "Italy",
    birthday: "8/27/2023",
  },
  {
    id: 25,
    name: "Karlotta",
    age: 42,
    email: "kleilo@mozilla.com",
    country: "Sweden",
    birthday: "1/21/2023",
  },
  {
    id: 26,
    name: "Stephi",
    age: 48,
    email: "smcnuttp@simplemachines.org",
    country: "United States",
    birthday: "8/27/2023",
  },
  {
    id: 27,
    name: "Daphna",
    age: 58,
    email: "drattenberieq@youku.com",
    country: "Nigeria",
    birthday: "1/8/2023",
  },
  {
    id: 28,
    name: "Kienan",
    age: 23,
    email: "kbridler@t-online.de",
    country: "Cuba",
    birthday: "11/3/2023",
  },
  {
    id: 29,
    name: "Lulu",
    age: 45,
    email: "lbeneytos@1und1.de",
    country: "Cuba",
    birthday: "9/4/2023",
  },
  {
    id: 30,
    name: "Yulma",
    age: 56,
    email: "yogavint@unesco.org",
    country: "Ukraine",
    birthday: "10/27/2023",
  },
  {
    id: 31,
    name: "Kiley",
    age: 64,
    email: "krosenhauptu@merriam-webster.com",
    country: "Panama",
    birthday: "4/13/2023",
  },
  {
    id: 32,
    name: "Ambrosius",
    age: 54,
    email: "asparkwillv@hexun.com",
    country: "Russia",
    birthday: "7/17/2023",
  },
  {
    id: 33,
    name: "Corenda",
    age: 78,
    email: "ctiffinw@stanford.edu",
    country: "Iraq",
    birthday: "3/17/2023",
  },
  {
    id: 34,
    name: "Edgard",
    age: 45,
    email: "ewestnedgex@macromedia.com",
    country: "Finland",
    birthday: "5/2/2023",
  },
  {
    id: 35,
    name: "Burtie",
    age: 22,
    email: "binoldy@oaic.gov.au",
    country: "Russia",
    birthday: "12/8/2023",
  },
  {
    id: 36,
    name: "Cheri",
    age: 51,
    email: "ccurtoysz@issuu.com",
    country: "China",
    birthday: "9/4/2023",
  },
  {
    id: 37,
    name: "Jaclyn",
    age: 25,
    email: "jfawson10@mayoclinic.com",
    country: "Sweden",
    birthday: "1/20/2023",
  },
  {
    id: 38,
    name: "Elise",
    age: 40,
    email: "egallimore11@hud.gov",
    country: "China",
    birthday: "9/25/2023",
  },
  {
    id: 39,
    name: "Cecilius",
    age: 74,
    email: "colifard12@google.co.uk",
    country: "Gambia",
    birthday: "6/26/2023",
  },
  {
    id: 40,
    name: "Rina",
    age: 43,
    email: "rmather13@paginegialle.it",
    country: "Brazil",
    birthday: "7/11/2023",
  },
  {
    id: 41,
    name: "Kissie",
    age: 76,
    email: "klefriec14@bigcartel.com",
    country: "Russia",
    birthday: "12/3/2023",
  },
  {
    id: 42,
    name: "Shayna",
    age: 71,
    email: "soliver15@umn.edu",
    country: "Ukraine",
    birthday: "12/14/2023",
  },
  {
    id: 43,
    name: "Basilius",
    age: 40,
    email: "bmorecomb16@icq.com",
    country: "Bosnia and Herzegovina",
    birthday: "11/22/2023",
  },
  {
    id: 44,
    name: "Jillayne",
    age: 64,
    email: "jgrono17@webmd.com",
    country: "Indonesia",
    birthday: "9/8/2023",
  },
  {
    id: 45,
    name: "Cherey",
    age: 31,
    email: "cphythian18@stumbleupon.com",
    country: "China",
    birthday: "11/6/2023",
  },
  {
    id: 46,
    name: "Suzy",
    age: 72,
    email: "sfills19@github.io",
    country: "Palestinian Territory",
    birthday: "5/21/2023",
  },
  {
    id: 47,
    name: "Hester",
    age: 36,
    email: "hchezelle1a@icio.us",
    country: "Philippines",
    birthday: "7/3/2023",
  },
  {
    id: 48,
    name: "Louise",
    age: 58,
    email: "lrounsivall1b@quantcast.com",
    country: "South Africa",
    birthday: "7/14/2023",
  },
  {
    id: 49,
    name: "Loy",
    age: 77,
    email: "lgather1c@jiathis.com",
    country: "North Korea",
    birthday: "2/4/2023",
  },
  {
    id: 50,
    name: "Clio",
    age: 72,
    email: "cbygraves1d@webnode.com",
    country: "Indonesia",
    birthday: "8/31/2023",
  },
];
